# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 18.10'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12'

- script: npm -v
  displayName: 'Npm version'

- script: 'rm -rf ~/.node-gyp'
  displayName: 'Install build essential'

- script: yarn install
  displayName: 'Install'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1


