# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install App Dependencies'

- script: |
    cd playwright-tests
    npm ci
    npx playwright install --with-deps
  displayName: 'Install Playwright Dependencies'

- script: |
    cd playwright-tests
    npx playwright test
  displayName: 'Run Playwright Tests'
  env:
    CI: 'true'
    BASE_URL: $(BASE_URL)
    BASE_ADMIN_URL: $(BASE_ADMIN_URL)
    QA_KEY: $(QA_KEY)

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'playwright-tests/test-results/junit.xml'
    testRunTitle: 'Playwright Tests'

- task: PublishPipelineArtifact@1
  condition: succeededOrFailed()
  inputs:
    targetPath: 'playwright-tests/playwright-report'
    artifact: 'playwright-report'
    publishLocation: 'pipeline'

- task: ArchiveFiles@2
  condition: succeeded()
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  condition: succeeded()


