@establishment_trading_name
Feature: Establishment Trading Name 

    Establishment address section validation

    @happy_path_SDB-4
    Scenario: happy path
        Given I open the url "establishment-trading-name"
        And I click on the element "estabTradingName.button"
        When I set "Test Trading Name" to the inputfield "estabTradingName.tradingNameInput"
        And I click on the element "estabTradingName.button"
        Then I expect the url to not contain "establishment-trading-name"

            @incomplete_form_SDB-4
    Scenario: user does not input a trading name
        Given I open the url "/cleansession"
        And I open the url "establishment-trading-name"
        When I click on the element "estabTradingName.button"
        Then I expect that element "estabTradingName.error" contains the text "Enter a valid establishment trading name"

    @invalid_trading_name_SDB-4
    Scenario: Invalid Trading Name
        Given I open the url "/cleansession"
        And I open the url "establishment-trading-name"
        When I set "This is text containing more than 255 characters. This is text containing more than 255 characters. This is text containing more than 255 characters. This is text containing more than 255 characters. This is text containing more than 255 characters. 012345" to the inputfield "estabTradingName.tradingNameInput"
        When I click on the element "estabTradingName.button"
        Then I expect that element "estabTradingName.error" contains the text "Enter a valid establishment trading name"
        And I expect that element "estabTradingName.tradingNameInput" contains the text ""

    @additional_trading_names
    Scenario: Additional trading names
        Given I open the url "/cleansession"
        And I open the url "establishment-trading-name"
        When I set "Test Trading Name" to the inputfield "estabTradingName.tradingNameInput"
        And I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        Then I expect the url to contain "establishment-trading-name-details?trading_name=Test+Trading+Name"
        And I expect that element "estabTradingName.additionalTradingNamePageTitle" contains the text "Add additional trading name"
        When I set "Test Trading Name 1" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"
        Then I expect the url to contain "establishment-trading-name"
        And I expect that element "estabTradingName.firstAdditionalTradingNameLabel" contains the text "Test Trading Name 1"
        Then I click on the element "estabTradingName.changeFirstTradingNameLink"
        And I expect that element "estabTradingName.additionalTradingNameInput" contains the text "Test Trading Name 1"
        When I set "Test Trading Name 2" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"
        Then I expect the url to contain "establishment-trading-name"
        And I expect that element "estabTradingName.firstAdditionalTradingNameLabel" contains the text "Test Trading Name 2"
        Then I click on the element "estabTradingName.deleteFirstAdditionalTradingNameBtn"
        And I expect that element "estabTradingName.firstAdditionalTradingNameLabel" is not visible
        Then I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        And I expect that element "estabTradingName.additionalTradingNameInput" contains the text ""
        When I set "Test Trading Name 3" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.cancelButton"
        Then I expect the url to contain "establishment-trading-name"
        And I expect that element "estabTradingName.firstAdditionalTradingNameLabel" is not visible
        
    @additional_trading_names_validation
    Scenario: Additional trading names validation
        Given I open the url "/cleansession"
        And I open the url "establishment-trading-name"
        When I set "Test Trading Name" to the inputfield "estabTradingName.tradingNameInput"
        And I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        Then I expect the url to contain "establishment-trading-name-details?trading_name=Test+Trading+Name"
        And I expect that element "estabTradingName.additionalTradingNamePageTitle" contains the text "Add additional trading name"
        When I set "Test Trading Name 1" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"
        Then I expect the url to contain "establishment-trading-name"
        And I expect that element "estabTradingName.firstAdditionalTradingNameLabel" contains the text "Test Trading Name 1"
        Then I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        And I expect that element "estabTradingName.additionalTradingNameInput" contains the text ""
        When I click on the element "estabTradingName.button"
        Then I expect that element "estabTradingName.error" contains the text "Enter a valid establishment trading name"
        When I set "This is text containing more than 255 characters. This is text containing more than 255 characters. This is text containing more than 255 characters. This is text containing more than 255 characters. This is text containing more than 255 characters. 012345" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"
        Then I expect that element "estabTradingName.error" contains the text "Enter a valid establishment trading name"   
        When I set "Test Trading Name 1" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"
        Then I expect the url to contain "establishment-trading-name"
        Then I click on the element "estabTradingName.button"
        And I expect that element "estabTradingName.errorAdditional" contains the text "You have entered an invalid number of additional trading names or a duplicate trading name. Please define up to 10 additional trading names and ensure that each entry is unique."
        Then I click on the element "estabTradingName.deleteFirstAdditionalTradingNameBtn"
        When I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        Then I expect the url to contain "establishment-trading-name-details?trading_name=Test+Trading+Name"
        And I expect that element "estabTradingName.additionalTradingNamePageTitle" contains the text "Add additional trading name"
        When I set "Test Trading Name 2" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"
        When I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        Then I expect the url to contain "establishment-trading-name-details?trading_name=Test+Trading+Name"
        And I expect that element "estabTradingName.additionalTradingNamePageTitle" contains the text "Add additional trading name"
        When I set "Test Trading Name 3" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"       
        When I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        Then I expect the url to contain "establishment-trading-name-details?trading_name=Test+Trading+Name"
        And I expect that element "estabTradingName.additionalTradingNamePageTitle" contains the text "Add additional trading name"
        When I set "Test Trading Name 4" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"    
        When I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        Then I expect the url to contain "establishment-trading-name-details?trading_name=Test+Trading+Name"
        And I expect that element "estabTradingName.additionalTradingNamePageTitle" contains the text "Add additional trading name"
        When I set "Test Trading Name 5" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"    
        When I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        Then I expect the url to contain "establishment-trading-name-details?trading_name=Test+Trading+Name"
        And I expect that element "estabTradingName.additionalTradingNamePageTitle" contains the text "Add additional trading name"
        When I set "Test Trading Name 6" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"   
        When I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        Then I expect the url to contain "establishment-trading-name-details?trading_name=Test+Trading+Name"
        And I expect that element "estabTradingName.additionalTradingNamePageTitle" contains the text "Add additional trading name"
        When I set "Test Trading Name 7" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"
        When I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        Then I expect the url to contain "establishment-trading-name-details?trading_name=Test+Trading+Name"
        And I expect that element "estabTradingName.additionalTradingNamePageTitle" contains the text "Add additional trading name"
        When I set "Test Trading Name 8" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"
        When I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        Then I expect the url to contain "establishment-trading-name-details?trading_name=Test+Trading+Name"
        And I expect that element "estabTradingName.additionalTradingNamePageTitle" contains the text "Add additional trading name"
        When I set "Test Trading Name 9" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"
        When I click on the element "estabTradingName.addAdditionalTradingNameBtn"
        Then I expect the url to contain "establishment-trading-name-details?trading_name=Test+Trading+Name"
        And I expect that element "estabTradingName.additionalTradingNamePageTitle" contains the text "Add additional trading name"
        When I set "Test Trading Name 10" to the inputfield "estabTradingName.additionalTradingNameInput"
        And I click on the element "estabTradingName.button"
        Then I expect element "estabTradingName.addAdditionalTradingNameBtn" is not visible
        When I click on the element "estabTradingName.button"
        Then I expect the url to contain "establishment-address-type"

