const landingPage = {
  heading: ".govuk-heading-xl",
  enterButton: "#main-content > div > div > div.gem-c-cards > ul > li > div > h2 > a",
  searchField: '[name="search"]',
  editHeading: ".govuk-heading-l",
  editButton:"#latable > td:nth-child(4) > a:nth-child(1)",
  countyName:'[name="local_council"]',
  successMessage: "#main-content > div > div > div > h1",
  button:".govuk-button",
  newCouncilName: ".govuk-panel__body",
  emailField: '[name="local_council_email"]',
  backLink: ".govuk-link",
  emailSummary: "#latable > td:nth-child(2) > p:nth-child(2)",
  tableField: "#main-content > div > table > tbody",
  numberField: '[name="local_council_phone_number"]',
  numberSummary: "#main-content > div > form > main > div > div > dl > div:nth-child(5) > dd.govuk-summary-list__value",
  addButton: "#main-content > div > a",
  idInput: '[name="_id"]',
  nameInput: '[name="local_council"]',
  emailInput: '[name="local_council_email"]',
  notifyEmailInput: '[name="local_council_notify_emails"]',
  phoneNumberInput: '[name="local_council_phone_number"]',
  countryInput: '[name="country"]',
  localUrlInput: '[name="local_council_url"]',
  countryDropdown: ".govuk-select",
  newCouncil: ".govuk-panel__body",
  deleteLink: "#latable > td:nth-child(4) > a:nth-child(2)",
  deleteCheckbox: '[name="confirm_delete"]',
};
export default landingPage ;