const registrationSummary = {
  button: "#continue-button",
  error: ".css-jdwgdl",
  operatorType: "#operator_type",
  companyName: "#operator_company_name",
  companyNumber: "#operator_company_house_number",
  operatorFirstName: "#operator_first_name",
  operatorLastName: "#operator_last_name",
  operatorEmail: "#operator_email",
  operatorPrimaryNumber: "#operator_primary_number",
  representativeName: "#contact_representative_name",
  representativeRole: "#contact_representative_role",
  representativeNumber: "#contact_representative_number",
  representativeEmail: "#contact_representative_email",
  tradingName: "#establishment_trading_name",
  establishmentType: "#establishment_type",
  establishmentPrimaryNumber: "#establishment_primary_number",
  establishmentSecondaryNumber: "#establishment_secondary_number",
  establishmentEmail: "#establishment_email",
  establishmentAddressStreet: "#establishment_street",
  foodActivities: "#import_export_activities",
  openingDays: "#opening_days_irregular",
  tradingStartDate: "#establishment_opening_date",
  customertype: "#customer_type",
  businessType: "#business_type",
  importExportActivities: "#import_export_activities",

  changeCompanyName: "#changeOperatorCompanyNameRow",
  changeOperatorType: "#changeOperatorTypeRow",
  changeCharityName: "#changeOperatorCharityNameRow",
  changeCharityNumber: "#changeOperatorCharityNumberRow",
  changeOperatorName: "#changeOperatorNameRow",
  changeOperatorContactDetails: "#changeOperatorContactDetailsRow",
  changeOperatorEmail: "#changeOperatorEmailRow",
  changeTradingName: "#changeEstablishmentTradingNameRow",
  changeEstablishmentAddress: "#changeEstablishmentAddressRow",
  changeEstablishmentContactDetails: "#changeEstablishmentContactDetailsRow",
  changeEstablishmentEmail: "#changeEstablishmentEmailRow",
  changeEstablishmentLocationType: "#changeEstablishmentLocationType",
  changeActivitiesBusinessImportExportRow:
    "#changeActivitiesBusinessImportExportRow",
  changeTradingStartDate: "#changeEstablishmentOpeningDateRow"
};

module.exports = registrationSummary;
