const registrationSummary = {
  button: ".govuk-button",
  error: ".govuk-error-message",
  operatorType: "#operator_type",
  companyName: "#operator_company_name",
  companiesNumber: "#operator_companies_house_number",
  operatorFirstName: "#operator_first_name",
  operatorLastName: "#operator_last_name",
  operatorEmail: "#operator_email",
  operatorPrimaryNumber: "#operator_primary_number",
  partnershipMainContact: "#main_partnership_contact",
  partnerOne: "#partners",
  partnerTwo: "#operatorPartnersRow>td>div:nth-child(2)",
  partnerThree: "#operatorPartnersRow>td>div:nth-child(3)",
  representativeName: "#contact_representative_name",
  representativeRole: "#contact_representative_role",
  representativeNumber: "#contact_representative_number",
  representativeEmail: "#contact_representative_email",
  tradingName: "#establishment_trading_name",
  establishmentType: "#establishment_type",
  establishmentPrimaryNumber: "#establishment_primary_number",
  establishmentSecondaryNumber: "#establishment_secondary_number",
  establishmentEmail: "#establishment_email",
  establishmentAddressStreet: "#establishment_address_line_2",
  foodActivities: "#import_export_activities",
  openingDays: "#opening_day_monday",
  tradingStartDate: "#establishment_opening_date",
  customertype: "#customer_type",
  businessType: "#business_type",
  importExportActivities: "#import_export_activities",
  changeCompanyName: "#changeOperatorCompanyNameRow",
  changeOperatorType: "#main-content > div > div > form > dl:nth-child(4) > div > dd.govuk-summary-list__actions > a",
  changeCharityName: "#changeOperatorCharityNameRow",
  changeCharityNumber: "#changeOperatorCharityNumberRow",
  changeOperatorName: "#changeOperatorNameRow",
  changeOperatorContactDetails: "#changeOperatorContactDetailsRow",
  changeOperatorEmail: "#main-content > div > div > form > dl:nth-child(8) > div > dd.govuk-summary-list__actions > a",
  changeTradingName: "#main-content > div > div > form > dl:nth-child(10) > div > dd.govuk-summary-list__actions",
  changeEstablishmentAddress: "#changeEstablishmentAddressRow",
  changeEstablishmentContactDetails: "#changeEstablishmentContactDetailsRow",
  changeEstablishmentEmail: "#changeEstablishmentEmailRow",
  changeEstablishmentLocationType: "#changeEstablishmentLocationType",
  changeActivitiesBusinessImportExportRow: "#changeActivitiesBusinessImportExportRow",
  changeTradingStartDate: "#establishment_opening_date",
  changeOpeningDays: "#changeEstablishmentOpeningDaysRow",
  waterSupply: "#water_supply"
};

module.exports = registrationSummary;
