const tradingStandardsChecks = {
  initialCheckInput: '[name="local_council_initial_check"]',
  regularCheckInput: '[name="local_council_regular_check"]',
  error: ".govuk-error-message",
  editHeading: "#main-content > div > main > div > div > h1",
  heading: ".govuk-heading-xl",
  enterButton: "#main-content > div > div > div.gem-c-cards > ul > li > div > h2 > a",
  button: ".govuk-button",
  searchField: '[name="search"]',
  searchButton: "#main-content > div > div > div:nth-child(1) > form > div > div:nth-child(4) > button",
  editButton: "#latable > td:nth-child(4) > a:nth-child(1)",
  successMessage: "#main-content > div > div > div > h1",
  viewCouncil: "#latable > td:nth-child(2) > p:nth-child(1) > a",
  viewInitialCheck: "#main-content > div > table > tbody > tr:nth-child(14) > td > table > tbody > tr > td:nth-child(1)",
  viewRegularCheck: "#main-content > div > table > tbody > tr:nth-child(14) > td > table > tbody > tr > td:nth-child(2)",
  checkChase: "#main-content > div > table > tbody > tr:nth-child(14) > td > table > tbody > tr > td:nth-child(3) > span",
  chaseCheckbox: '[name="local_council_chase_check"]',
  backLink: ".govuk-link",
  welcomeTitle: "#main-content > div > div > div.govuk-grid-column-full > h1",
};
export default tradingStandardsChecks ;